[platformio]
src_dir = src

[env:esp32c3]
platform = espressif32@6.10.0
board = esp32-c3-devkitm-1
framework = espidf
platform_packages = platformio/framework-espidf@3.50400.0
monitor_speed = 115200
build_flags = -DIOLINK_PLATFORM_FREERTOS
